/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;

public class Library {

    public void test() {
        JdbcTemplate foo = new JdbcTemplate();
    }
    public boolean someLibraryMethod() {
        return true;
    }
}
